In [8]:
import pandas as pd
import numpy as np

In [9]:
full_matchups = pd.read_csv("Tournament Matchups.csv")
display(full_matchups)

,YEAR,BY YEAR NO,TEAM NO,TEAM,SEED,ROUND,CURRENT ROUND,SCORE
0,2025,2140,1141,Auburn,1,4,64,83
1,2025,2139,1145,Alabama St.,16,64,64,63
2,2025,2138,1119,Louisville,8,64,64,75
3,2025,2137,1134,Creighton,9,32,64,89
4,2025,2136,1114,Michigan,5,16,64,68
...,...,...,...,...,...,...,...,...
2135,2008,5,43,Kansas,1,1,4,84
2136,2008,4,37,Memphis,1,2,4,78
2137,2008,3,13,UCLA,1,4,4,63
2138,2008,2,43,Kansas,1,1,2,75
2139,2008,1,37,Memphis,1,2,2,68

In [10]:
matchups = full_matchups.copy()
matchups['temp_col'] = 1
matchups['match_num'] = (matchups.groupby('YEAR')['temp_col'].cumsum() - 1) // 2 + 1
display(matchups)

,YEAR,BY YEAR NO,TEAM NO,TEAM,SEED,ROUND,CURRENT ROUND,SCORE,temp_col,match_num
0,2025,2140,1141,Auburn,1,4,64,83,1,1
1,2025,2139,1145,Alabama St.,16,64,64,63,1,1
2,2025,2138,1119,Louisville,8,64,64,75,1,2
3,2025,2137,1134,Creighton,9,32,64,89,1,2
4,2025,2136,1114,Michigan,5,16,64,68,1,3
...,...,...,...,...,...,...,...,...,...,...
2135,2008,5,43,Kansas,1,1,4,84,1,61
2136,2008,4,37,Memphis,1,2,4,78,1,62
2137,2008,3,13,UCLA,1,4,4,63,1,62
2138,2008,2,43,Kansas,1,1,2,75,1,63
2139,2008,1,37,Memphis,1,2,2,68,1,63

In [11]:
recent = matchups[matchups['YEAR'] == 2025]
display(recent)

,YEAR,BY YEAR NO,TEAM NO,TEAM,SEED,ROUND,CURRENT ROUND,SCORE,temp_col,match_num
0,2025,2140,1141,Auburn,1,4,64,83,1,1
1,2025,2139,1145,Alabama St.,16,64,64,63,1,1
2,2025,2138,1119,Louisville,8,64,64,75,1,2
3,2025,2137,1134,Creighton,9,32,64,89,1,2
4,2025,2136,1114,Michigan,5,16,64,68,1,3
...,...,...,...,...,...,...,...,...,...,...
121,2025,2019,1131,Florida,1,1,4,79,1,61
122,2025,2018,1132,Duke,1,4,4,67,1,62
123,2025,2017,1126,Houston,1,2,4,70,1,62
124,2025,2016,1131,Florida,1,1,2,65,1,63
125,2025,2015,1126,Houston,1,2,2,63,1,63

In [12]:
results_dict = {}

matchups['seed_pairing'] = matchups.groupby(['match_num', 'YEAR'])['SEED'].transform('sum') - matchups['SEED']
winner_seed = matchups.loc[matchups.groupby(['match_num', 'YEAR'])['SCORE'].idxmax(), ['match_num', 'YEAR', 'SEED']]
winner_seed = winner_seed.set_index(['match_num', 'YEAR'])['SEED']

matchups['winner_seed'] = matchups.set_index(['match_num', 'YEAR']).index.map(winner_seed)
matchups = matchups.drop_duplicates(subset=['match_num', 'YEAR'])
display(matchups)

for _, row in matchups.iterrows():
    if f"{row['SEED']}-{row['seed_pairing']}" not in results_dict:
        results_dict[f"{row['SEED']}-{row['seed_pairing']}"] = [0, 0]

    if row['winner_seed'] == row['SEED']:
        results_dict[f"{row['SEED']}-{row['seed_pairing']}"][0] += 1
    else:
        results_dict[f"{row['SEED']}-{row['seed_pairing']}"][1] += 1

print(results_dict)

,YEAR,BY YEAR NO,TEAM NO,TEAM,SEED,ROUND,CURRENT ROUND,SCORE,temp_col,match_num,seed_pairing,winner_seed
0,2025,2140,1141,Auburn,1,4,64,83,1,1,16,1
2,2025,2138,1119,Louisville,8,64,64,75,1,2,9,9
4,2025,2136,1114,Michigan,5,16,64,68,1,3,12,5
6,2025,2134,1092,Texas A&M,4,32,64,80,1,4,13,4
8,2025,2132,1112,Mississippi,6,16,64,71,1,5,11,6
...,...,...,...,...,...,...,...,...,...,...,...,...
2130,2008,10,37,Memphis,1,2,8,85,1,59,2,1
2132,2008,8,13,UCLA,1,4,8,76,1,60,3,1
2134,2008,6,31,North Carolina,1,4,4,66,1,61,1,1
2136,2008,4,37,Memphis,1,2,4,78,1,62,1,1
2138,2008,2,43,Kansas,1,1,2,75,1,63,1,1

{'1-16': [66, 2], '8-9': [35, 33], '5-12': [40, 28], '4-13': [53, 15], '6-11': [35, 33], '3-14': [60, 8], '7-10': [40, 27], '2-15': [61, 7], '1-9': [29, 3], '5-4': [13, 21], '6-3': [8, 23], '10-2': [6, 19], '1-8': [28, 7], '12-4': [3, 18], '11-3': [12, 18], '7-2': [11, 25], '1-5': [14, 6], '6-2': [2, 7], '1-4': [24, 8], '3-10': [3, 1], '3-2': [10, 14], '1-2': [13, 8], '1-3': [11, 3], '1-1': [12, 0], '5-13': [8, 0], '11-14': [4, 0], '11-2': [3, 8], '4-6': [1, 0], '4-11': [0, 1], '11-1': [0, 1], '7-15': [1, 4], '16-9': [0, 2], '6-15': [1, 0], '9-4': [2, 0], '3-7': [5, 4], '8-4': [3, 3], '5-6': [2, 0], '9-3': [1, 1], '5-2': [3, 1], '4-3': [3, 1], '5-9': [1, 0], '3-15': [2, 1], '11-10': [2, 2], '4-2': [1, 1], '8-15': [1, 0], '1-10': [3, 1], '2-8': [0, 2], '2-1': [2, 3], '8-1': [0, 1], '6-7': [2, 0], '8-12': [0, 1], '1-6': [2, 0], '1-11': [3, 2], '12-2': [0, 1], '12-13': [5, 2], '1-12': [7, 0], '2-3': [0, 1], '3-1': [0, 4], '9-5': [1, 1], '11-7': [1, 0], '9-11': [0, 1], '4-7': [1, 3], '7-1': [0, 2], '6-14': [4, 0], '10-15': [2, 0], '2-2': [2, 0], '8-2': [2, 0], '1-7': [0, 1], '7-8': [1, 0], '9-13': [1, 0], '9-2': [1, 0], '4-4': [1, 0], '1-13': [1, 0], '5-3': [0, 1], '11-8': [0, 1], '3-8': [1, 0], '5-5': [1, 0], '5-1': [0, 1]}

In [13]:
new_matchups = pd.DataFrame(columns=['seed', 'curr_round', 'match_num', 'seed_pairing'])
new_matchups['seed'] = [1, 16, 8, 9, 5, 12, 4, 13, 6, 11, 3, 14, 7, 10, 2, 15]*4
new_matchups['curr_round'] = 64
new_matchups['temp_col'] = 1
new_matchups['match_num'] = (new_matchups['temp_col'].cumsum() - 1) // 2 + 1
new_matchups['seed_pairing'] = new_matchups.groupby(['match_num', 'curr_round'])['seed'].transform('sum') - new_matchups['seed']
new_matchups = new_matchups.drop_duplicates(subset=['match_num', 'curr_round'])
random_beta = lambda x: np.random.beta(results_dict.get(f"{x['seed']}-{x['seed_pairing']}", [1, 1]), results_dict.get(f"{x['seed']}-{x['seed_pairing']}", [1, 1])[1] + 1)
random_winner = lambda x: np.random.choice([x['seed'], x['seed_pairing']], p=[random_beta(x)[0], 1-random_beta(x)[0]])
new_matchups['winner'] = new_matchups.apply(random_winner, axis=1)
new_matchups.drop(columns=['temp_col'], inplace=True)
display(new_matchups)

ValueError: probabilities do not sum to 1